fix: Allow function access keys to be used without explicit write permission (this reflects the SocialDB contract implementation) (#11)
As can be seen if running the tests without the fix, we get the error
message `ERROR: Social DB requires more storage deposit, but we cannot
cover it when signing transaction with a Function Call only access key`
if using a function access key that does not have explicit write
permission, but comes from the account that we want to write to. This
should not fail, and this PR reproduces and fixes the issue.

Here is the output of running the unit tests without the fix:

```bash
test tests::test_get_deposit_other_account_no_explicit_write_permission ... ok
test tests::test_get_deposit_own_account_explicit_write_permission ... ok
test tests::test_get_deposit_own_account_no_explicit_write_permission ... FAILED
test tests::test_get_deposit_same_account_function_access_key_with_required_deposit ... ok
test tests::test_get_deposit_write_permission_function_access_key_with_required_deposit ... ok

failures:

---- tests::test_get_deposit_own_account_no_explicit_write_permission stdout ----
Error: ERROR: Social DB requires more storage deposit, but we cannot cover it when signing transaction with a Function Call only access key

Location:
    src/lib.rs:191:17
thread 'tests::test_get_deposit_own_account_no_explicit_write_permission' panicked at src/lib.rs:465:17:
get_deposit should not fail when using a public key belonging to the target account, even without explicit write permission. Error Message:
ERROR: Social DB requires more storage deposit, but we cannot cover it when signing transaction with a Function Call only access key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::test_get_deposit_own_account_no_explicit_write_permission
```

In addition this PR adds github codespaces setup, and a workflow for
running the unit tests. The "code-style" CI workflow is also updated to
use `ubuntu-latest` and `rust-cache` because it failed with the current
setup.

fixes https://github.com/NEAR-DevHub/neardevhub-bos/issues/897